### ISSUE TITLE
I can't access the percentage view 

### ISSUE THREAD

**Issue by manolomartinez** [EliotJones/HnTrends#1]
Screenshot attached. This is Firefox on Android. 
![Screenshot_20200205-100407](https://user-images.githubusercontent.com/2140956/73826936-f079c980-47fe-11ea-8cc5-43930eb68b52.png)
Am I missing something? Is this the right region of the page where the access to the percentage view should be?

Thanks,
Manolo

**Comment by EliotJones** [comment]
Hi there, it's this button here (though admittedly it's too grey and not very noticeable):
![image](https://user-images.githubusercontent.com/7862346/73829288-a1ca3080-47fa-11ea-9f21-26f27c4a61a5.png)

**Comment by manolomartinez** [comment]
Thanks, Eliot. It's noticeable enough 😅. One thing I tried was clicking on the y-axis legend, to see if it took me to other possible options. You might want to consider putting a menu there.
